/** Stable diagnostic codes for vision setup (VISION-14). */
export const VISION_DIAGNOSTIC_CODES = {
  VISION_PROJECT_UNSUPPORTED: "VISION_PROJECT_UNSUPPORTED",
  VISION_NO_LIBRARIES: "VISION_NO_LIBRARIES",
  VISION_DEFAULT_PROVIDER_MISMATCH: "VISION_DEFAULT_PROVIDER_MISMATCH",
  VISION_CONFIG_ERROR: "VISION_CONFIG_ERROR",
  VISION_CAMERA_NOT_CONFIGURED: "VISION_CAMERA_NOT_CONFIGURED",
  VISION_HARDWARE_NAME_MISMATCH: "VISION_HARDWARE_NAME_MISMATCH",
  VISION_ENDPOINT_AMBIGUOUS: "VISION_ENDPOINT_AMBIGUOUS",
  VISION_HOST_UNREACHABLE: "VISION_HOST_UNREACHABLE",
  VISION_LIMELIGHT_HOST_UNRESOLVED: "VISION_LIMELIGHT_HOST_UNRESOLVED",
  VISION_SELECTION_REQUIRED: "VISION_SELECTION_REQUIRED",
  VISION_DASHBOARD_URL_AMBIGUOUS: "VISION_DASHBOARD_URL_AMBIGUOUS",
  VISION_DASHBOARD_UNREACHABLE: "VISION_DASHBOARD_UNREACHABLE",
  VISION_BRIDGE_NOT_SCAFFOLDED: "VISION_BRIDGE_NOT_SCAFFOLDED",
  VISION_PIPELINE_ARTIFACT_ERROR: "VISION_PIPELINE_ARTIFACT_ERROR",
  VISION_COMPETITION_NETWORK_CAUTION: "VISION_COMPETITION_NETWORK_CAUTION",
} as const;

export type VisionDiagnosticCode =
  (typeof VISION_DIAGNOSTIC_CODES)[keyof typeof VISION_DIAGNOSTIC_CODES];
