import type { OpModeKind, OpModeStyle } from "../../opmode/types.js";
import { renderEasyOpenCvPipelineSource } from "../easyopencv/templates.js";
import type { VisionCodegenKind } from "./types.js";
import { VISION_CODEGEN_GENERATED_MARKER } from "./constants.js";

export interface VisionCodegenTemplateInput {
  packageName: string;
  className: string;
  displayName: string;
  opModeKind: OpModeKind;
  style: OpModeStyle;
  group?: string;
  cameraName: string;
  pipelineClassName?: string;
  limelightTableName?: string;
  useDashboardStream?: boolean;
  robotConfigName?: string;
}

function escapeJavaString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function opModeAnnotation(input: VisionCodegenTemplateInput): string {
  const type = input.opModeKind === "teleop" ? "TeleOp" : "Autonomous";
  const parts = [`name="${escapeJavaString(input.displayName)}"`];
  if (input.group?.trim()) {
    parts.push(`group="${escapeJavaString(input.group.trim())}"`);
  }
  return `@${type}(${parts.join(", ")})`;
}

function generatedHeader(kind: string): string {
  return `/**
 * ${VISION_CODEGEN_GENERATED_MARKER} — ${kind}.
 * Java TeamCode only. Review imports against your FTC SDK version before deploying.
 */`;
}

export function renderEasyOpenCvPipelineFile(input: VisionCodegenTemplateInput): string {
  const pipelineClass = input.pipelineClassName ?? `${input.className}Pipeline`;
  return renderEasyOpenCvPipelineSource({
    packageName: input.packageName,
    className: pipelineClass,
  }).replace(
    "EasyOpenCV pipeline stub generated by FTC Dev Tools (VISION-09).",
    `${VISION_CODEGEN_GENERATED_MARKER} — EasyOpenCV pipeline.`,
  );
}

export function renderEasyOpenCvOpModeSource(input: VisionCodegenTemplateInput): string {
  const pipelineClass = input.pipelineClassName ?? `${input.className}Pipeline`;
  const annotation = opModeAnnotation(input);
  const configHint = input.robotConfigName ? `Robot config: ${input.robotConfigName}. ` : "";
  const dashboardImport = input.useDashboardStream
    ? "import com.acmerobotics.dashboard.FtcDashboard;\n"
    : "";
  const dashboardField = input.useDashboardStream ? "\n    private FtcDashboard dashboard;" : "";
  const dashboardInit = input.useDashboardStream
    ? "\n        dashboard = FtcDashboard.getInstance();"
    : "";
  const dashboardStream = input.useDashboardStream
    ? "\n            dashboard.startCameraStream(webcam);"
    : "";
  const dashboardStop = input.useDashboardStream
    ? "\n            dashboard.stopCameraStream(webcam);"
    : "";

  return `package ${input.packageName};

import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.${input.opModeKind === "teleop" ? "TeleOp" : "Autonomous"};
import com.qualcomm.robotcore.hardware.WebcamName;
import org.openftc.easyopencv.OpenCvWebcam;
import org.openftc.easyopencv.OpenCvWebcamFactory;
${dashboardImport}
${generatedHeader("EasyOpenCV OpMode")}

${annotation}
public class ${input.className} extends LinearOpMode {
    private OpenCvWebcam webcam;${dashboardField}

    @Override
    public void runOpMode() {
        // ${configHint}Camera: "${input.cameraName}"
        ${pipelineClass} pipeline = new ${pipelineClass}();
        webcam = OpenCvWebcamFactory.getInstance()
                .createWebcam(hardwareMap.get(WebcamName.class, "${input.cameraName}"), pipeline);${dashboardInit}

        webcam.openCameraDeviceAsync();
        while (!isStopRequested() && !webcam.isOpen()) {
            idle();
        }

        telemetry.addData("Camera", "${input.cameraName}");
        telemetry.update();
        waitForStart();

        try {${dashboardStream}
            while (opModeIsActive()) {
                telemetry.addData("FPS", webcam.getFrameProcessingTimeMs());
                telemetry.update();
            }
        } finally {
            if (webcam != null) {
                webcam.closeCameraDevice();${dashboardStop}
            }
        }
    }
}
`;
}

export function renderVisionPortalAprilTagOpModeSource(input: VisionCodegenTemplateInput): string {
  const annotation = opModeAnnotation(input);
  const configHint = input.robotConfigName ? `Robot config: ${input.robotConfigName}. ` : "";

  return `package ${input.packageName};

import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.${input.opModeKind === "teleop" ? "TeleOp" : "Autonomous"};
import com.qualcomm.robotcore.hardware.WebcamName;
import org.firstinspires.ftc.vision.VisionPortal;
import org.firstinspires.ftc.vision.apriltag.AprilTagProcessor;

${generatedHeader("VisionPortal AprilTag")}

${annotation}
public class ${input.className} extends LinearOpMode {
    private VisionPortal visionPortal;

    @Override
    public void runOpMode() {
        // ${configHint}Camera: "${input.cameraName}"
        AprilTagProcessor aprilTag = new AprilTagProcessor.Builder()
                .setDrawTagID(true)
                .setDrawAxes(true)
                .build();

        visionPortal = new VisionPortal.Builder()
                .setCamera(hardwareMap.get(WebcamName.class, "${input.cameraName}"))
                .addProcessor(aprilTag)
                .build();

        telemetry.addData("Camera", "${input.cameraName}");
        telemetry.update();
        waitForStart();

        try {
            while (opModeIsActive()) {
                telemetry.addData("AprilTag detections", aprilTag.getDetections().size());
                telemetry.update();
            }
        } finally {
            closeVisionPortal();
        }
    }

    private void closeVisionPortal() {
        if (visionPortal != null) {
            visionPortal.close();
            visionPortal = null;
        }
    }
}
`;
}

export function renderVisionPortalColorOpModeSource(input: VisionCodegenTemplateInput): string {
  const annotation = opModeAnnotation(input);
  const configHint = input.robotConfigName ? `Robot config: ${input.robotConfigName}. ` : "";

  return `package ${input.packageName};

import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.${input.opModeKind === "teleop" ? "TeleOp" : "Autonomous"};
import com.qualcomm.robotcore.hardware.WebcamName;
import org.firstinspires.ftc.vision.VisionPortal;
import org.firstinspires.ftc.vision.color.ColorProcessor;

${generatedHeader("VisionPortal color processor")}

${annotation}
public class ${input.className} extends LinearOpMode {
    private VisionPortal visionPortal;

    @Override
    public void runOpMode() {
        // ${configHint}Camera: "${input.cameraName}"
        ColorProcessor colorProcessor = new ColorProcessor.Builder()
                .setDrawContours(true)
                .build();

        visionPortal = new VisionPortal.Builder()
                .setCamera(hardwareMap.get(WebcamName.class, "${input.cameraName}"))
                .addProcessor(colorProcessor)
                .build();

        telemetry.addData("Camera", "${input.cameraName}");
        telemetry.update();
        waitForStart();

        try {
            while (opModeIsActive()) {
                telemetry.addData("Color blobs", colorProcessor.getDetections().size());
                telemetry.update();
            }
        } finally {
            closeVisionPortal();
        }
    }

    private void closeVisionPortal() {
        if (visionPortal != null) {
            visionPortal.close();
            visionPortal = null;
        }
    }
}
`;
}

export function renderLimelightOpModeSource(input: VisionCodegenTemplateInput): string {
  const tableName = input.limelightTableName ?? "limelight";
  const annotation = opModeAnnotation({
    ...input,
    opModeKind: "teleop",
    displayName: input.displayName,
  });

  return `package ${input.packageName};

import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;

${generatedHeader("Limelight NetworkTables integration")}

${annotation}
public class ${input.className} extends LinearOpMode {
    private NetworkTable limelight;
    private int activePipeline = 0;

    @Override
    public void runOpMode() {
        // --- ${VISION_CODEGEN_GENERATED_MARKER}: Limelight init ---
        NetworkTableInstance inst = NetworkTableInstance.getDefault();
        limelight = inst.getTable("${tableName}");
        limelight.getEntry("pipeline").setNumber(activePipeline);

        telemetry.addLine("Limelight table: ${tableName}");
        telemetry.addLine("D-pad up/down: switch pipeline index");
        telemetry.update();
        waitForStart();

        while (opModeIsActive()) {
            handlePipelineSwitch();
            readLimelightResults();
            telemetry.update();
        }
    }

    private void handlePipelineSwitch() {
        if (gamepad1.dpad_up) {
            activePipeline = Math.max(0, activePipeline - 1);
            limelight.getEntry("pipeline").setNumber(activePipeline);
        } else if (gamepad1.dpad_down) {
            activePipeline = activePipeline + 1;
            limelight.getEntry("pipeline").setNumber(activePipeline);
        }
        telemetry.addData("Pipeline", activePipeline);
    }

    private void readLimelightResults() {
        // --- ${VISION_CODEGEN_GENERATED_MARKER}: Limelight result loop ---
        double tv = limelight.getEntry("tv").getDouble(0.0);
        boolean targetValid = tv == 1.0;
        double tx = limelight.getEntry("tx").getDouble(0.0);
        double ty = limelight.getEntry("ty").getDouble(0.0);
        double ta = limelight.getEntry("ta").getDouble(0.0);

        telemetry.addData("Target valid", targetValid);
        telemetry.addData("tx", tx);
        telemetry.addData("ty", ty);
        telemetry.addData("ta", ta);
    }
}
`;
}

export function renderDashboardStreamOpModeSource(input: VisionCodegenTemplateInput): string {
  const annotation = opModeAnnotation({
    ...input,
    opModeKind: "teleop",
    displayName: input.displayName,
  });
  const configHint = input.robotConfigName ? `Robot config: ${input.robotConfigName}. ` : "";

  return `package ${input.packageName};

import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.hardware.WebcamName;
import com.acmerobotics.dashboard.FtcDashboard;
import org.firstinspires.ftc.vision.VisionPortal;

${generatedHeader("FTC Dashboard camera stream")}

${annotation}
public class ${input.className} extends LinearOpMode {
    private VisionPortal visionPortal;
    private FtcDashboard dashboard;

    @Override
    public void runOpMode() {
        // ${configHint}Camera: "${input.cameraName}"
        dashboard = FtcDashboard.getInstance();
        visionPortal = new VisionPortal.Builder()
                .setCamera(hardwareMap.get(WebcamName.class, "${input.cameraName}"))
                .build();
        dashboard.startCameraStream(visionPortal);

        telemetry.addLine("Dashboard camera stream active.");
        telemetry.update();
        waitForStart();

        try {
            while (opModeIsActive()) {
                idle();
            }
        } finally {
            if (dashboard != null && visionPortal != null) {
                dashboard.stopCameraStream(visionPortal);
            }
            closeVisionPortal();
        }
    }

    private void closeVisionPortal() {
        if (visionPortal != null) {
            visionPortal.close();
            visionPortal = null;
        }
    }
}
`;
}

export function renderVisionCodegenSource(
  kind: VisionCodegenKind,
  input: VisionCodegenTemplateInput,
): { files: Array<{ relativePath: string; content: string }> } {
  const javaRoot = input.packageName.split(".").join("/");
  const basePath = `TeamCode/src/main/java/${javaRoot}`;

  switch (kind) {
    case "easyopencv": {
      const pipelineClass = input.pipelineClassName ?? `${input.className}Pipeline`;
      return {
        files: [
          {
            relativePath: `${basePath}/${pipelineClass}.java`.replace(/\\/g, "/"),
            content: renderEasyOpenCvPipelineFile(input),
          },
          {
            relativePath: `${basePath}/${input.className}.java`.replace(/\\/g, "/"),
            content: renderEasyOpenCvOpModeSource(input),
          },
        ],
      };
    }
    case "visionportal-apriltag":
      return {
        files: [
          {
            relativePath: `${basePath}/${input.className}.java`.replace(/\\/g, "/"),
            content: renderVisionPortalAprilTagOpModeSource(input),
          },
        ],
      };
    case "visionportal-color":
      return {
        files: [
          {
            relativePath: `${basePath}/${input.className}.java`.replace(/\\/g, "/"),
            content: renderVisionPortalColorOpModeSource(input),
          },
        ],
      };
    case "limelight":
      return {
        files: [
          {
            relativePath: `${basePath}/${input.className}.java`.replace(/\\/g, "/"),
            content: renderLimelightOpModeSource(input),
          },
        ],
      };
    case "dashboard-stream":
      return {
        files: [
          {
            relativePath: `${basePath}/${input.className}.java`.replace(/\\/g, "/"),
            content: renderDashboardStreamOpModeSource(input),
          },
        ],
      };
    default:
      return { files: [] };
  }
}
