export interface EasyOpenCvPipelineTemplateInput {
  packageName: string;
  className: string;
}

export interface EasyOpenCvWebcamInitTemplateInput {
  packageName: string;
  cameraName: string;
  pipelineClassName: string;
  useDashboardStream?: boolean;
}

export function renderEasyOpenCvPipelineSource(input: EasyOpenCvPipelineTemplateInput): string {
  return `package ${input.packageName};

import org.opencv.core.Mat;
import org.openftc.easyopencv.OpenCvPipeline;

/**
 * EasyOpenCV pipeline stub generated by FTC Dev Tools (VISION-09).
 * Tune processing in processFrame(); avoid Android-only APIs for desktop replay compatibility.
 */
public class ${input.className} extends OpenCvPipeline {
    @Override
    public Mat processFrame(Mat input) {
        return input;
    }
}
`;
}

export function renderEasyOpenCvWebcamInitSnippet(
  input: EasyOpenCvWebcamInitTemplateInput,
): string {
  const dashboardBlock = input.useDashboardStream
    ? `
        FtcDashboard.getInstance().startCameraStream(webcam);`
    : "";

  return `import com.qualcomm.robotcore.hardware.WebcamName;
import org.openftc.easyopencv.OpenCvWebcam;
import org.openftc.easyopencv.OpenCvWebcamFactory;
import ${input.packageName}.${input.pipelineClassName};
${input.useDashboardStream ? "import com.acmerobotics.dashboard.FtcDashboard;\n" : ""}
// EasyOpenCV webcam setup (VISION-09 template)
${input.pipelineClassName} pipeline = new ${input.pipelineClassName}();
OpenCvWebcam webcam = OpenCvWebcamFactory.getInstance()
        .createWebcam(hardwareMap.get(WebcamName.class, "${input.cameraName}"), pipeline);
webcam.openCameraDeviceAsync();${dashboardBlock}
`;
}
