import { MODULE_MANIFEST_SCHEMA_VERSION, type ModuleManifest } from "./types.js";

/** Built-in module catalog (ADR-0001 taxonomy). */
export const BUILTIN_MODULES: readonly ModuleManifest[] = [
  {
    schemaVersion: MODULE_MANIFEST_SCHEMA_VERSION,
    id: "core-platform",
    displayName: "Core Platform",
    layer: "core",
    summary:
      "Project discovery, build/deploy, devices, diagnostics, readiness, and provider registries.",
    provides: ["logging"],
  },
  {
    schemaVersion: MODULE_MANIFEST_SCHEMA_VERSION,
    id: "vision-lab",
    displayName: "Vision Lab",
    layer: "capability",
    summary: "IDE-integrated camera development, overlays, calibration, and vision diagnostics.",
    dependsOn: ["core-platform"],
    provides: ["vision", "code-generation", "replay"],
    epicIssue: 48,
  },
  {
    schemaVersion: MODULE_MANIFEST_SCHEMA_VERSION,
    id: "ftc-replay",
    displayName: "FTC Replay",
    layer: "capability",
    summary: "Session recording and offline replay for telemetry, logs, hardware, and vision.",
    dependsOn: ["core-platform"],
    provides: ["replay", "logging"],
    epicIssue: 143,
  },
  {
    schemaVersion: MODULE_MANIFEST_SCHEMA_VERSION,
    id: "ftc-sim",
    displayName: "FTC Sim",
    layer: "capability",
    summary: "Pluggable simulator runtimes and virtual hardware.",
    dependsOn: ["core-platform"],
    provides: ["simulation"],
    experimental: true,
    epicIssue: 145,
  },
  {
    schemaVersion: MODULE_MANIFEST_SCHEMA_VERSION,
    id: "hardware-lab",
    displayName: "Hardware Lab",
    layer: "capability",
    summary: "Localization devices, hardware validation, and advanced hwmap workflows.",
    dependsOn: ["core-platform"],
    provides: ["hardware", "localization"],
    epicIssue: 144,
  },
  {
    schemaVersion: MODULE_MANIFEST_SCHEMA_VERSION,
    id: "tuning-lab",
    displayName: "Tuning Lab",
    layer: "capability",
    summary: "PID and mechanism tuning workflows.",
    dependsOn: ["core-platform"],
    provides: ["logging"],
    experimental: true,
    epicIssue: 146,
  },
  {
    schemaVersion: MODULE_MANIFEST_SCHEMA_VERSION,
    id: "autonomous-studio",
    displayName: "Autonomous Studio",
    layer: "workflow",
    summary: "Composed workflow for autonomous path development and validation.",
    dependsOn: ["core-platform", "vision-lab", "ftc-replay"],
    provides: ["path-planning", "code-generation"],
    experimental: true,
    epicIssue: 154,
  },
  {
    schemaVersion: MODULE_MANIFEST_SCHEMA_VERSION,
    id: "match-analysis",
    displayName: "Match Analysis",
    layer: "workflow",
    summary: "Composed workflow for post-match replay and telemetry analysis.",
    dependsOn: ["core-platform", "ftc-replay"],
    provides: ["replay", "dashboard"],
    experimental: true,
    epicIssue: 153,
  },
];
