import type { IntegrationManifest } from "./types.js";

/** Built-in integration catalog. Single source of truth until external manifests load. */
export const BUILTIN_INTEGRATIONS: readonly IntegrationManifest[] = [
  {
    id: "official-ftc-sdk",
    displayName: "FTC SDK (official)",
    category: "official",
    classification: "official",
    capabilities: ["commands", "vision", "hardware", "logging"],
    supportedSdkVersions: ["8.0+"],
    supportedFtcDevToolsVersions: ["0.1.0+"],
    robotLanguage: "java",
    desktopLanguage: "typescript",
    replaySupport: false,
    simulationSupport: false,
    documentationUrl: "https://ftc-docs.firstinspires.org/",
    experimental: false,
    deprecated: false,
    summary: "Official FIRST Tech Challenge Android SDK and robot controller.",
  },
  {
    id: "pedro-pathing",
    displayName: "Pedro Pathing",
    category: "pathing",
    classification: "supported",
    capabilities: ["path-planning", "localization", "code-generation"],
    supportedSdkVersions: ["8.2+"],
    supportedFtcDevToolsVersions: ["0.1.0+"],
    robotLanguage: "java",
    desktopLanguage: "typescript",
    replaySupport: false,
    simulationSupport: false,
    documentationUrl: "https://pedropathing.com/",
    experimental: false,
    deprecated: false,
    cliCommand: "pedro",
    summary: "Path planning and localization; first-class ftc pedro commands.",
  },
  {
    id: "ftc-dashboard",
    displayName: "FTC Dashboard",
    category: "dashboard",
    classification: "supported",
    capabilities: ["dashboard", "logging", "replay"],
    supportedSdkVersions: ["8.0+"],
    supportedFtcDevToolsVersions: ["0.2.0+"],
    robotLanguage: "java",
    desktopLanguage: "typescript",
    replaySupport: true,
    simulationSupport: false,
    documentationUrl: "https://acmerobotics.github.io/ftc-dashboard/",
    experimental: false,
    deprecated: false,
    summary: "Community telemetry dashboard; interoperability planned (VISION-06).",
  },
  {
    id: "visionportal",
    displayName: "VisionPortal (FTC SDK)",
    category: "vision",
    classification: "official",
    capabilities: ["vision"],
    supportedSdkVersions: ["8.1+"],
    supportedFtcDevToolsVersions: ["0.2.0+"],
    robotLanguage: "java",
    desktopLanguage: "typescript",
    replaySupport: true,
    simulationSupport: true,
    documentationUrl: "https://ftc-docs.firstinspires.org/programming_resources/vision/",
    experimental: false,
    deprecated: false,
    summary: "Official SDK vision pipeline; Vision Lab target (VISION-08).",
  },
  {
    id: "easyopencv",
    displayName: "EasyOpenCV",
    category: "vision",
    classification: "supported",
    capabilities: ["vision"],
    supportedSdkVersions: ["8.0+"],
    supportedFtcDevToolsVersions: ["0.2.0+"],
    robotLanguage: "java",
    desktopLanguage: "typescript",
    replaySupport: true,
    simulationSupport: false,
    documentationUrl: "https://github.com/OpenFTC/EasyOpenCV",
    experimental: false,
    deprecated: false,
    summary: "OpenCV wrapper for FTC; Vision Lab adapter target (VISION-09).",
  },
  {
    id: "limelight",
    displayName: "Limelight Vision",
    category: "vision",
    classification: "supported",
    capabilities: ["vision", "localization"],
    supportedSdkVersions: ["8.0+"],
    supportedFtcDevToolsVersions: ["0.2.0+"],
    robotLanguage: "java",
    desktopLanguage: "typescript",
    replaySupport: true,
    simulationSupport: false,
    documentationUrl: "https://docs.limelightvision.io/",
    experimental: false,
    deprecated: false,
    summary: "Limelight Vision network coprocessors; Vision Lab provider target (VISION-04).",
  },
  {
    id: "road-runner",
    displayName: "Road Runner",
    category: "pathing",
    classification: "legacy",
    capabilities: ["path-planning", "localization"],
    supportedSdkVersions: ["8.0+"],
    supportedFtcDevToolsVersions: [],
    robotLanguage: "java",
    desktopLanguage: "typescript",
    replaySupport: false,
    simulationSupport: true,
    documentationUrl: "https://github.com/acmerobotics/road-runner",
    experimental: true,
    deprecated: false,
    summary: "Deferred; Pedro Pathing is the committed pathing focus.",
  },
  {
    id: "nextftc",
    displayName: "NextFTC",
    category: "framework",
    classification: "experimental",
    capabilities: ["commands"],
    supportedSdkVersions: ["10.0+"],
    supportedFtcDevToolsVersions: [],
    robotLanguage: "java",
    desktopLanguage: "typescript",
    replaySupport: false,
    simulationSupport: false,
    documentationUrl: "https://github.com/Skyhawk246/NextFTC",
    experimental: true,
    deprecated: false,
    summary: "Evaluation epic; adapter framework candidate.",
  },
  {
    id: "ftclib",
    displayName: "FTCLib",
    category: "framework",
    classification: "experimental",
    capabilities: ["commands", "hardware"],
    supportedSdkVersions: ["8.0+"],
    supportedFtcDevToolsVersions: [],
    robotLanguage: "java",
    desktopLanguage: "typescript",
    replaySupport: false,
    simulationSupport: false,
    documentationUrl: "https://docs.ftclib.org/",
    experimental: true,
    deprecated: false,
    summary: "Evaluation epic; adapter framework candidate.",
  },
  {
    id: "pinpoint",
    displayName: "GoBilda Pinpoint",
    category: "localization",
    classification: "supported",
    capabilities: ["localization", "hardware"],
    supportedSdkVersions: ["8.0+"],
    supportedFtcDevToolsVersions: ["0.2.0+"],
    robotLanguage: "java",
    desktopLanguage: "typescript",
    replaySupport: true,
    simulationSupport: false,
    documentationUrl: "https://www.gobilda.com/",
    experimental: false,
    deprecated: false,
    summary: "Odometry board; Hardware Lab target.",
  },
  {
    id: "otos",
    displayName: "SparkFun OTOS",
    category: "localization",
    classification: "supported",
    capabilities: ["localization", "hardware"],
    supportedSdkVersions: ["8.0+"],
    supportedFtcDevToolsVersions: ["0.2.0+"],
    robotLanguage: "java",
    desktopLanguage: "typescript",
    replaySupport: true,
    simulationSupport: false,
    documentationUrl: "https://www.sparkfun.com/",
    experimental: false,
    deprecated: false,
    summary: "Optical tracking odometry; Hardware Lab target.",
  },
];
